### PR TITLE
Update composer.json

### PR DESCRIPTION
**Pull request by tm69**
bugfix installation laravel 9.x

### CODE REVIEW

**Review by fcanteiro — CHANGES_REQUESTED** [review]
bugfix installation laravel 9.x

**Review by atymic — APPROVED** [review]

**Comment by shawkiIIalasy** [comment]
@fcanteiro @atymic Please check

**Comment by OthmanAdlan** [comment]
@atymic @fcanteiro May you please check this PR, thanks in advance.

**Comment by yul-klj** [comment]
@tm69 re-request @fcanteiro to review the pull request please, needs this

**Comment by frankieeedeee** [comment]
Hey @tm69, thanks for flagging this! This has now been resolved in #12 and released in version `2.0.1` of the package.

The version constraint has been corrected to `^9.0.2`, (see #9 for context on why this is set for 9.0._**2**_)

Thanks again!

**Pull request closed without merging**
