### PR TITLE
feat: init commit

### PR DESCRIPTION
**Pull request by frankieeedeee**
Initial push of source code from [original repository](https://github.com/frankieeedeee/google-chat-laravel)

On the initial merge, the following can be expected:

- Failing tests
  - This is because there is a single end-to-end test which posts to a (muted) Google Chat room. This webhook secret must be set in the repo in order for the workflow tests to complete.
- Invalid Badges
  - The correct badge URLs have not been set, as the repository needed to be created first. I'll go ahead update those once this is merged.

### CODE REVIEW

**Comment by frankieeedeee** [comment]
Hey @atymic! Thanks for setting this repo up, just pushing the initial source code here. Once that's merged, I'll go ahead and update the repo webhook secret so tests can complete successfully, and update the badges with the correct repo url. Let me know if I can help out with anything else in the meantime! Cheers.

**Comment by frankieeedeee** [comment]
Hey @atymic - Just wondering if you had a chance to review this one yet? Cheers!

**Comment by atymic** [comment]
Sorry, didn't get a notif. 🙈

**Comment by atymic** [comment]
Packagist:
https://packagist.org/packages/laravel-notification-channels/google-chat

**Comment by atymic** [comment]
Website PR when you tag first release, give me a ping.
https://github.com/laravel-notification-channels/website/pull/40/files

**Comment by frankieeedeee** [comment]
Thanks @atymic! Will work on that first tag and publish shortly - Cheers!

**Pull request merged**
